### ISSUE TITLE
world change during /msg convo switches chat channel

### ISSUE THREAD

**Issue by psiber-on-uncovery** [uncovery/uncovery_me#195] opened 2016-02-01 14:11 UTC
Recieving intermittent reports of nuisance bug

switching world changes chat channel to designer.

Report record started 01/02/16 to identify patterns
unrecorded (2-3)
01/02/16 Psychodrea (master)

**Comment by uncovery** [comment] 2016-02-01 14:52
Very weird, I am not sure I can fix that.

**Comment by psiber-on-uncovery** [comment] 2016-02-07 01:27
Further testing performed by alleywig, linklux and psychodrea revealed that the change only happens when you are already in a conversation with another user. The channel changed to is not always designer, but appears rank dependent.

To reproduce:
> go to empire or kingdom
> /msg <playername> (to initiate a private messaging channel)
> change world via any means /home /tp / tpaccept etc all reproduce.

**Comment by psiber-on-uncovery** [comment] 2016-02-07 08:31
Devotedworker has quit (Quit: Connection closed for inactivity)
<Fortifier> psiber: It seems to be code-side
<Fortifier> psiber: When you change worlds, the server tries to 'refocus' your channel, so that you aren't in a not-allowed channel for the world. You might have a permission wrong somewhere (For the PM channel, if there is one).
<Fortifier> psiber: I don't think PM's are actually a channel are they?
<psiber> if you type /msg user
<psiber> but noa rgument afterwards
<Fortifier> Is it actually a proper channel though?
<psiber> it creates a persistent private messaging channel
<psiber> no idea
<Fortifier> Like is there PM channel permissions?
<psiber> no idea, but adding permission nodes to users when they open a private messaging conversation with somebody seems cumbersome :S
<Fortifier> psiber: Seems like an issue in HeroChat then
<psiber> could be, i need to do some more testing first
<Fortifier> I can't see why it would cause this.. soo
<psiber> i think that you are right, that there is a security check on world change
<Fortifier> psiber: No I've actually checked the code, there is :)
<psiber> but i think its been broadform applied to all channels, not jsut public ones
<Fortifier> psiber: but it should handle PM's the same as other channels
<Fortifier>   public void onPlayerChangeWorld(PlayerChangedWorldEvent event)
<Fortifier>   {
<Fortifier>     Herochat.getChatterManager().getChatter(event.getPlayer()).refocus();
<Fortifier>   }
<psiber> ah. and there is no node to allow for persistent pm conversations between worlds?
<Fortifier> Where refocus checks if they have permissions etc
<psiber> ok, so the refocus function doesnt check if its a pm conversation
<Fortifier> psiber: It checks any channel
<psiber> but instead looks for a security node based on that specific channels name? which is unknown to an end user opening a pm?
<psiber> ok. can you tell me the naming structure for pm channels perchance?
<Fortifier> psiber: no idea
<Fortifier> I can only suggest trying the channel as "conversation"
<psiber> ok. but does each different "conversation" have its own name? logic would say yes.
<psiber> which means trying to add perms is fairly fruitless
<Fortifier> psiber: I don't even know
<Fortifier> psiber: As I say you can try the channel in your permissions as "conversation"
<Fortifier> But I'm quite sure most of the PM channel stuff is hardcoded in
<psiber> yes. smells like a logic error to me. will try conversation as the channel and see what happens

**Comment by psiber-on-uncovery** [comment] 2016-02-07 08:33
<Fortifier> psiber: If you can't come to any conclusions - go here and file a bug report http://redmine.hc.to/projects/hc-heroes/issues?set_filter=1&tracker_id=1

**Comment by psiber-on-uncovery** [comment] 2016-02-07 09:36
<psiber> yeah ok, so the refocus event doesnt seem to handle conversation channels as should be the case.
<Fortifier> psiber: So issue time!
<psiber> the channel name syntax is convoplayer1player2
<Fortifier> http://redmine.hc.to/projects/hc-heroes/issues?set_filter=1&tracker_id=1
<psiber> and when you change world, because it hasn't had allowed worlds specified
<psiber> it pops you out
<psiber> im just going to cheat and force allowed worlds into the channel by console on a /msg command
<psiber> just as simple.

**Comment by psiber-on-uncovery** [comment] 2016-02-07 09:39
/ch set convopsibereisele2847 crossworld true

should be run each time a new /msg player conversation is begun where the name is a concatenated version of the two players.

**Comment by psiber-on-uncovery** [comment] 2016-02-07 09:50
order is independent on the command, convopsibereisele2847 or convoeisele2847psiber works independently because of the nick flag in the channel info

**Comment by uncovery** [comment] 2017-03-02 02:01
I would close this here now since we have a new chat plugin and the issue is most likely resolved?

**Comment by psiber-on-uncovery** [comment] 2017-05-10 09:54
Resolved by new chat plugin. can be closed.

**Closed** 2017-05-10 10:58 UTC
Labels: bug, to be tested
